steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "$_USERNAME" > /root/username
        echo "$_INSTANCE_NAME" > /root/instance_name
        gcloud compute scp --recurse ./app $(cat /root/username)@$(cat $GITHUB_WORKSPACE/secrets/EXTERNAL_IP):~/"$(cat /root/instance_name)" --zone=$(cat $GITHUB_WORKSPACE/secrets/ZONE) --ssh-key-file=/root/.ssh/id_rsa
        gcloud compute ssh $(cat /root/username)@$(cat $GITHUB_WORKSPACE/secrets/EXTERNAL_IP) --zone=$(cat $GITHUB_WORKSPACE/secrets/ZONE) --command "sudo systemctl restart my-flask-app"
options:
  logging: CLOUD_LOGGING_ONLY
secrets:
  - kmsKeyName: projects/<your-project>/locations/global/keyRings/<your-key-ring>/cryptoKeys/<your-key>
    secretEnv:
      _USERNAME: <username-secret>
      _INSTANCE_NAME: <instance-name-secret>
