steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh git-gcp-vm \
        --zone=us-central1-a \
        --project=$PROJECT_ID \
        --command='sudo apt update' \
        --command='sudo apt upgrade -y' \
        --command='sudo apt install php' \
        --command='sudo apt install php-mysql' 
        env:
      - 'LOGGING_OPTION=CLOUD_LOGGING_ONLY'

logsBucket: onramp-sample-bucket