steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "$_INSTANCE_NAME" > /root/instance_name
        echo "$_EXTERNAL_IP" > /root/external_ip
        echo "$_SSH_PRIVATE_KEY" > /root/.ssh/id_rsa
        chmod 600 /root/.ssh/id_rsa
        gcloud compute scp --recurse ./app "$(cat /root/instance_name)":~/app --zone="$(cat /root/zone)" --ssh-key-file=/root/.ssh/id_rsa
        gcloud compute ssh "$(cat /root/instance_name)" --zone="$(cat /root/zone)" --command "sudo systemctl restart my-flask-app"
options:
  logging: CLOUD_LOGGING_ONLY
secrets:
  - kmsKeyName: projects/<your-project-id>/locations/global/keyRings/<your-key-ring>/cryptoKeys/<your-key>
    secretEnv:
      _INSTANCE_NAME: ''
      _EXTERNAL_IP: ''
      _SSH_PRIVATE_KEY: ''
