steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh git-gcp-vm \
        --zone=us-central1-a \
        --project=$PROJECT_ID \
        --command='sudo apt update' \
        --command='sudo apt upgrade -y' \
        --command='sudo apt install php -y'
    env:
      - 'LOGGING_OPTION=CLOUD_LOGGING_ONLY'
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/shailenevonence/cloud_build_using_github.git', '/workspace/repo']
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "steps:" > /workspace/repo/cloudbuild.yaml
        echo "  - name: 'gcr.io/cloud-builders/gcloud'" >> /workspace/repo/cloudbuild.yaml
        echo "    entrypoint: 'bash'" >> /workspace/repo/cloudbuild.yaml
        echo "    args:" >> /workspace/repo/cloudbuild.yaml
        echo "      - '-c'" >> /workspace/repo/cloudbuild.yaml
        echo "      - |" >> /workspace/repo/cloudbuild.yaml
        echo "        gcloud compute ssh git-gcp-vm \\" >> /workspace/repo/cloudbuild.yaml
        echo "        --zone=us-central1-a \\" >> /workspace/repo/cloudbuild.yaml
        echo "        --project=\$PROJECT_ID \\" >> /workspace/repo/cloudbuild.yaml
        echo "        --command='sudo apt update' \\" >> /workspace/repo/cloudbuild.yaml
        echo "        --command='sudo apt upgrade -y' \\" >> /workspace/repo/cloudbuild.yaml
        echo "        --command='sudo apt install php -y'" >> /workspace/repo/cloudbuild.yaml
    dir: '/workspace/repo'
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute scp --recurse /workspace/repo git-gcp-vm:/testfolder/ \
        --zone=us-central1-a \
        --project=$PROJECT_ID
logsBucket: onramp-sample-bucket
