steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud compute ssh git-gcp-vm \
      --zone=us-central1-a \
      --project=$PROJECT_ID \
      --command='sudo touch /testcloudbuild' \
      --command='sudo mkdir /myapp' \
      --command='cd /myapp' \
      --command='pip install -r requirements.txt && gunicorn app:app --bind 0.0.0.0:8080'
  env:
    - 'LOGGING_OPTION=CLOUD_LOGGING_ONLY'

logsBucket: onramp-sample-bucket
